# apiVersion: v1
# kind: Service
# metadata:
#   name: my-prometheus
#   namespace: monitoring
# spec:
#   type: ClusterIP
#   selector:
#     prometheus: my-prometheus
#   ports:
#     - name: web
#       port: 9090
#       targetPort: 9090