apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logging-monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - grafana.68.233.108.177.nip.io
      - kibana.68.233.108.177.nip.io
      - prometheus.68.233.108.177.nip.io
      - alertmanager.68.233.108.177.nip.io
      - elasticsearch.68.233.108.177.nip.io
    secretName: monitoring-tls

  rules:
    # Grafana
    - host: grafana.68.233.108.177.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 80

    # Kibana
    - host: kibana.68.233.108.177.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kibana
                port:
                  number: 5601

    # Prometheus
    - host: prometheus.68.233.108.177.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090

    # Alertmanager
    - host: alertmanager.68.233.108.177.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093

    # Elasticsearch (optional)
    - host: elasticsearch.68.233.108.177.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: elasticsearch
                port:
                  number: 9200