apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres-secret
  namespace: efk
type: Opaque
stringData:
  postgres-user: grafana
  postgres-password: ChangeMePostgres123!
  postgres-db: grafana