apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels: { app: alertmanager }
spec:
  replicas: 1
  selector:
    matchLabels: { app: alertmanager }
  template:
    metadata:
      labels: { app: alertmanager }
    spec:
      containers:
        - name: alertmanager
          image: docker.io/prom/alertmanager:v0.27.0
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: am-config
              mountPath: /etc/alertmanager
      volumes:
        - name: am-config
          configMap:
            name: alertmanager-config
